export type AgentType = "Scaffolder" | "Researcher" | "Refactorer"; // Types of agents for plan steps

export interface PlanStep {
  id: string; // Unique identifier for the step
  title: string; // Step title/summary
  description: string; // Step detailed description
  agent: AgentType; // Agent responsible for this step
  status: "pending" | "in-progress" | "done" | "error"; // Current status of the step
  outputUri?: string; // Optional URI of output generated by the step
  error?: string; // Optional error message if step failed
}

export interface Plan {
  request?: string; // Optional original user request
  steps: PlanStep[]; // List of steps in the plan
  suggestions?: string[]; // Optional dynamic suggestions based on plan state
}